[[core-features]]
= Reactor 核心特性

Reactor 项目的主要 artifact 是 `reactor-core`,这是一个基于 Java 8 的实现了响应式流规范 (Reactive Streams specification)的响应式库.

Reactor 引入了实现 `Publisher` 的响应式类 `Flux` 和 `Mono`,以及丰富的操作方式. 一个 `Flux` 对象代表一个包含 0..N 个元素的响应式序列,而一个 `Mono` 对象代表一个包含 零/一个(0..1)元素的结果.

这种区别为这俩类型带来了语义上的信息——表明了异步处理逻辑所面对的元素基数.比如, 一个 HTTP 请求产生一个响应,所以对其进行 `count` 操作是没有多大意义的.表示这样一个 结果的话,应该用 `Mono<HttpResponse>` 而不是 `Flux<HttpResponse>`,因为要置于其上的 操作通常只用于处理 0/1 个元素.

有些操作可以改变基数,从而需要切换类型.比如,`count` 操作用于 `Flux`,但是操作 返回的结果是 `Mono<Long>`.

[[flux]]
== `Flux`, 包含 0-N 个元素的异步序列

下图显示了 `Flux` 如何传输元素:

image::{image-dir}/marbles/flux.svg[Flux]

`Flux<T>` 是一个能够发出 0 到 N 个元素的标准的 `Publisher<T>`,它会被一个 "错误(error)"  或 "完成(completion)" 信号终止.
就像在响应式流规范中规定的那样,这三种类型的信号被翻译为面向下游的 `onNext`,`onComplete` 和 `onError` 方法.

由于多种不同的信号可能性,`Flux` 可以作为一种通用的响应式类型.注意,所有的信号事件, 包括代表终止的信号事件都是可选的: 如果没有 `onNext` 事件但是有一个 `onComplete` 事件,
那么发出的就是 空的 有限序列,但是去掉 `onComplete` 那么得到的就是一个 无限的 空序列. 当然,无限序列也可以不是空序列,比如,`Flux.interval(Duration)` 生成的是一个 `Flux<Long>`, 这就是一个无限地周期性发出规律 ticks 的时钟序列.

[[mono]]
== `Mono`, 异步的 0-1 结果

下图显示了 `Mono` 如何传输元素:

image::{image-dir}/marbles/mono.svg[Mono]

`Mono<T>` 是一种特殊的 `Publisher<T>`, 它通过 `onNext`  信号最多发出一个元素,然后终止于一个 `onComplete` 信号 (成功的 `Mono`,值可有可无 ) 或一个 `onError` 信号 (失败的 `Mono`).

大多数  `Mono` 的实现都希望在调用 `onNext` 之后立即在 `Subscriber` 上调用 `onComplete`。`Mono.never()` 是一个异常值:它不发出任何信号，这在技术上不是禁止的，尽管在测试之外不是非常有用。另一方面，`onNext` 和 `onError` 的组合是显式禁止的。

`Mono` 只适用其中一部分可用于 `Flux` 的操作.比如,(两个 `Mono` 的)结合类操作可以忽略其中之一 而发出另一个 `Mono`,也可以将两个都发出,对于后一种情况会切换为一个 `Flux`.

例如,`Mono#concatWith(Publisher)` 返回一个 `Flux`,而 `Mono#then(Mono)` 返回另一个 `Mono`.

注意,`Mono` 可以用于表示“空”的只有完成概念的异步处理(比如 `Runnable`).这种用 `Mono<Void>` 来创建.

== 简单的创建和订阅 Flux 或 Mono 的方法

最简单的上手 `Flux` 和 `Mono` 的方式就是使用相应类提供的多种工厂方法之一.

比如,如果要创建一个 `String` 的序列,你可以直接列举它们,或者将它们放到一个集合里然后用来创建 Flux,如下:

====
[source,java]
----
Flux<String> seq1 = Flux.just("foo", "bar", "foobar");

List<String> iterable = Arrays.asList("foo", "bar", "foobar");
Flux<String> seq2 = Flux.fromIterable(iterable);
----
====

工厂方法的其他例子如下:

====
[source,java]
----
Mono<String> noData = Mono.empty(); <1>

Mono<String> data = Mono.just("foo");

Flux<Integer> numbersFromFiveToSeven = Flux.range(5, 3); <2>
----
<1> 注意,即使没有值,工厂方法仍然采用通用的返回类型.
<2> 第一个参数是 range 的开始,第二个参数是要生成的元素个数.
====

在订阅(subscribe)的时候,`Flux` 和 `Mono` 使用 Java 8 lambda 表达式. `.subscribe()` 方法有多种不同的方法签名,你可以传入各种不同的 lambda 形式的参数来定义回调.如下所示:

[[subscribeMethods]]
.基于 lambda 的对 `Flux` 的订阅(subscribe)
====
[source,java]
----
subscribe(); <1>

subscribe(Consumer<? super T> consumer); <2>

subscribe(Consumer<? super T> consumer,
          Consumer<? super Throwable> errorConsumer); <3>

subscribe(Consumer<? super T> consumer,
          Consumer<? super Throwable> errorConsumer,
          Runnable completeConsumer); <4>

subscribe(Consumer<? super T> consumer,
          Consumer<? super Throwable> errorConsumer,
          Runnable completeConsumer,
          Consumer<? super Subscription> subscriptionConsumer); <5>
----
<1> 订阅并触发序列.
<2> 对每一个生成的元素进行消费.
<3> 对正常元素进行消费,也对错误进行响应.
<4> 对正常元素和错误均有响应,还定义了序列正常完成后的回调.
<5> 对正常元素、错误和完成信号均有响应, 同时也定义了对该 `subscribe` 方法返回的 `Subscription` 执行的回调.
====

TIP: 以上方法会返回一个 `Subscription` 的引用,如果不再需要更多元素你可以通过它来取消订阅. 取消订阅时, 源头会停止生成新的数据,并清理相关资源.取消和清理的操作在 Reactor 中是在 接口 `Disposable` 中定义的.

include::subscribe-details.adoc[]

include::subscribe-backpressure.adoc[]

//the leveloffset seems to be absolute from root
include::producing.adoc[leveloffset=2]

[[schedulers]]
== Threading and Schedulers(线程和调度器)

Reactor, 就像 RxJava,也可以被认为是 并发无关(concurrency agnostic) 的.意思就是, 它并不强制要求任何并发模型.更进一步,它将选择权交给开发者.不过,它还是提供了一些方便 进行并发执行的库.

在 Reactor 中,执行模式以及执行过程取决于所使用的 Scheduler. Scheduler 是一个拥有广泛实现类的抽象接口. Schedulers 类提供的静态方法用于达成如下的执行环境:

`Flux` 和 `Mono` 不会创建线程.取而代之的是,大多数操作符会继续在前一个操作符的线程中工作. 除非指定,否则 topmost 运算符(source)本身运行在进行  `subscribe()`  调用的线程上. 以下示例在新线程中运行 `Mono`:

====
[source,java]
----
public static void main(String[] args) throws InterruptedException {
  final Mono<String> mono = Mono.just("hello "); //<1>

  Thread t = new Thread(() -> mono
      .map(msg -> msg + "thread ")
      .subscribe(v -> //<2>
          System.out.println(v + Thread.currentThread().getName()) //<3>
      )
  )
  t.start();
  t.join();

}
----
<1> `Mono<String>` 在 `main` 线程中运行.
<2> 但是,它是在线程 `Thread-0` 中订阅的. .
<3> 结果, `map` 和 `onNext` 回调实际上都在 `Thread-0` 中运行
====

上面的代码产生以下输出:

====
[source]
----
hello thread Thread-0
----
====

在 Reactor 中,执行模式以及执行过程取决于所使用的 `Scheduler`. https://projectreactor.io/docs/core/release/api/reactor/core/scheduler/Scheduler.html[`Scheduler`] 是一个拥有广泛实现类类似 `ExecutorService` 的调度职责 的抽象接口.
尤其是充当时钟并启用更广泛的实现方式(测试的虚拟时间,trampolining 或 即时调度 等)

https://projectreactor.io/docs/core/release/api/reactor/core/scheduler/Schedulers.html[`Schedulers`] 类提供的静态方法用于达成如下的执行环境:

* 没有执行上下文 (`Schedulers.immediate()`): 在处理时,提交的 `Runnable` 将被直接在当前线程中执行(可以视为“空对象”或无操作 `Scheduler`).
* 可重用的单线程 (`Schedulers.single()`). 注意,这个方法对所有调用者都提供同一个线程来使用, 直到该调度器(Scheduler)被废弃.如果你想使用专一的线程,就对每一个调用使用 `Schedulers.newSingle()` .
* 无限弹性线程池 (`Schedulers.elastic()`): 此选项不再是首选,因为它倾向于隐藏背压问题并导致线程过多(请参见下文)使用  `Schedulers.boundedElastic()`.
* 有限弹性线程池 (`Schedulers.boundedElastic()`). 像其前身 `elastic()` 一样 ,它根据需要创建一个线程池,重用空闲线程.线程池如果空闲时间过长 (默认为 60s)就会被废弃.与  `elastic()` 不同的是,它可以支持
你创建线程的个数(默认为 CPU 核数*10),达到上限后,最多可提交 `10` 万个任务,并在线程可用时重新调度(当延迟调度时,延迟在线程可用时开始),对于 I/O 阻塞的场景比较适用. `Schedulers.boundedElastic()` 能够方便地给一个阻塞 的任务分配它自己的线程,
从而不会妨碍其他任务和资源,见 <<faq.wrap-blocking,如何包装一个同步阻塞的调用 ?>>.使用新线程不会给系统带来太大压力.
* 固定大小线程池 (`Schedulers.parallel()`). 所创建线程池的大小与 CPU 个数等同.

此外,你还可以使用 `Schedulers.fromExecutorService(ExecutorService)` 基于现有的 `ExecutorService` 创建 `Scheduler`.(虽然不太建议,不过你也可以使用 `Executor` 来创建).

你也可以使用 `newXXX` 方法来创建不同的调度器.比如 `Schedulers.newElastic(yourScheduleName)` 创建一个新的名为 `yourScheduleName` 的弹性调度器.

[WARNING]
====
虽然 `boundedElastic` 可以帮助避免传统阻塞代码,但 `single` 和 `parallel` 则不行. 结果,使用 Reactor 阻塞的 API(`block()`, `blockFirst()`, `blockLast()` (以及在默认的  `single` 和 `parallel`  调度程序中迭代到 `toIterable()` 或 `toStream()` ))会抛出 `IllegalStateException` 异常.

通过创建实现 `NonBlocking` 接口的 `Thread` 实例,还可以将自定义调度程序标记为 "non blocking only".
====

一些操作符默认会使用一个指定的调度器(通常也允许开发者调整为其他调度器)例如, 通过工厂方法 `Flux.interval(Duration.ofMillis(300))`  生成的每 300ms 打点一次的 `Flux<Long>`, 默认情况下使用的是 `Schedulers.parallel()`,下边的代码演示了如何将其装换为 `Schedulers.single()`:

====
[source,java]
----
Flux.interval(Duration.ofMillis(300), Schedulers.newSingle("test"))
----
====

Reactor 提供了两种在响应式链中调整调度器 `Scheduler` 的方法: `publishOn` 和 `subscribeOn`. 它们都接受一个 `Scheduler` 作为参数,从而可以改变调度器.但是 `publishOn` 在链中出现的位置 是有讲究的,而 `subscribeOn` 则无所谓.要理解它们的不同,你首先要理解 <<reactive.subscribe,nothing happens until you subscribe>>.

在 Reactor 中,当你在操作链上添加操作符的时候,你可以根据需要在 `Flux` 和 `Mono` 的实现中包装其他的 `Flux` 和 `Mono`.一旦你订阅(subscribe)了它,一个 `Subscriber` 的链 就被创建了,一直向上到第一个 `publisher` .这些对开发者是不可见的,开发者所能看到的是最外一层的 `Flux` (或 `Mono`)和 `Subscription`,但是具体的任务是在中间这些跟操作符相关的 `subscriber` 上处理的.

基于此,我们仔细研究一下 `publishOn` 和 `subscribeOn` 这两个操作符:

=== The `publishOn` Method

`publishOn` 的用法和处于订阅链(subscriber chain)中的其他操作符一样.它将上游 信号传给下游,同时执行指定的调度器 `Scheduler` 的某个工作线程上的回调.
它会 改变后续的操作符的执行所在线程 (直到下一个 `publishOn` 出现在这个链上).如下所示:

* `Scheduler` 选择的一个线程更改执行上下文
* 根据规范,onNext调用是按顺序发生的,因此这会占用一个线程
* 除非他们在特定的 `Scheduler` 上工作,否则 `publishOn` 之后的操作符将继续在同一线程上执行

以下示例使用 `publishOn` 方法:

====
[source,java]
----
Scheduler s = Schedulers.newParallel("parallel-scheduler", 4); //<1>

final Flux<String> flux = Flux
    .range(1, 2)
    .map(i -> 10 + i)  //<2>
    .publishOn(s)  //<3>
    .map(i -> "value " + i);  //<4>

new Thread(() -> flux.subscribe(System.out::println));  //<5>
----
<1> 创建一个有 4 个线程的 `Scheduler` 实例
<2> 第一个 `map` 操作在  <5> 中匿名线程上执行.
<3> `publishOn` 将整个列表切换到从 <1> 选取的 线程 上.
<4> 第二个 `map` 在<1>的线程上运行.
<5> 此匿名线程是在 _subscription_ 时产生的线程.输出在最新的执行上下文中,输出 `publishOn` 中的内容.
====

=== The `subscribeOn` Method

`subscribeOn` 用于订阅(subscription)过程,作用于那个向上的订阅链(发布者在被订阅 时才激活,订阅的传递方向是向上游的).所以,无论你把 `subscribeOn` 至于操作链的什么位置,
它都会影响到源头的线程执行环境(context). 但是,它不会影响到后续的 `publishOn`,后者仍能够切换其后操作符的线程执行环境.

* 更改整个操作链所订阅的线程
* 从 `Scheduler` 中选择一个线程

NOTE: 实际上仅考虑链中最早的 `SubscribeOn` 调用.

以下示例使用 `subscribeOn` 方法:

====
[source,java]
----
Scheduler s = Schedulers.newParallel("parallel-scheduler", 4); //<1>

final Flux<String> flux = Flux
    .range(1, 2)
    .map(i -> 10 + i)  //<2>
    .subscribeOn(s)  //<3>
    .map(i -> "value " + i);  //<4>

new Thread(() -> flux.subscribe(System.out::println));  //<5>
----
<1> 创建一个有 4 个线程的 `Scheduler` 实例
<2> 第一个 `map` 操作在这四个线程之一上执行.
<3> ...因为 `subscriptionOn` 会从订阅时间(<5>)开始切换整个序列.
<4> 第二个 `map` 也运行在同一线程上.
<5> 这个匿名线程是最初进行  _subscription_ 的那个线程,但是 `subscribeOn` 立即将其转移到 scheduler 四个之一的线程.
====

[[error.handling]]
== 处理错误

TIP: 如果想了解有哪些可用于错误处理的操作符,请参考 <<which.errors,the relevant operator decision tree>>.

在响应式流中,错误(error)是终止(terminal)事件.当有错误发生时,它会导致流序列停止, 并且错误信号会沿着操作链条向下传递,直至遇到你定义的 `Subscriber` 及其 `onError` 方法.

这样的错误还是应该在应用层面解决的.比如,你可能会将错误信息显示在用户界面,或者通过某个 REST 端点(endpoint)发出.因此,订阅者(subscriber)的 `onError` 方法是应该定义的.

WARNING: 如果没有定义,`onError` 会抛出 `UnsupportedOperationException`.你可以接下来再 检测错误,并通过 `Exceptions.isErrorCallbackNotImplemented` 方法捕获和处理它.

Reactor 还提供了其他的用于在链中处理错误的方法,即错误处理操作(error-handling operators).

====
[source,java]
----
Flux.just(1, 2, 0)
    .map(i -> "100 / " + i + " = " + (100 / i)) //this triggers an error with 0
    .onErrorReturn("Divided by zero :("); // error handling example
----
====

IMPORTANT: 在你了解错误处理操作符之前,你必须牢记 响应式流中的任何错误都是一个终止事件. 即使用了错误处理操作符,也不会让源头流序列继续.
而是将 `onError` 信号转化为一个 新的 序列 的开始.换句话说,它代替了被终结的 上游 流序列.

现在我们来逐个看看错误处理的方法.需要的时候我们会同时用到命令式编程风格的 `try` 代码块来作比较.

=== “错误处理”方法

你也许熟悉在 try-catch 代码块中处理异常的几种方法.常见的包括如下几种:

* 捕获并返回一个静态的默认值.
* 捕获并执行一个异常处理方法.
* 捕获并动态计算一个候补值来顶替.
* 捕获,并再包装为某一个 业务相关的异常,然后再抛出 `BusinessException`.
* 捕获,记录错误日志,然后继续抛出.
* 使用 `finally` 来清理资源,或使用 Java 7 引入的 `"try-with-resource"`.

以上所有这些在 Reactor 都有相应的基于 error-handling 操作符处理方式.

在开始研究这些操作符之前,我们先准备好响应式链(reactive chain)方式和 try-catch 代码块方式(以便对比).

当订阅的时候,位于链结尾的 `onError` 回调方法和 `catch` 块类似,一旦有  `Exception` ,执行过程会跳入到 catch:

====
[source,java]
----
Flux<String> s = Flux.range(1, 10)
    .map(v -> doSomethingDangerous(v)) // <1>
    .map(v -> doSecondTransform(v)); // <2>
s.subscribe(value -> System.out.println("RECEIVED " + value), // <3>
            error -> System.err.println("CAUGHT " + error) // <4>
);
----
<1> 执行 map 转换,有可能抛出异常.
<2> 如果没问题,执行第二个 map 转换操作.
<3> 所有转换成功的值都打印出来.
<4> 一旦有错误,序列(sequence)终止,并打印错误信息.
====

这与 try/catch 代码块是类似的:

====
[source,java]
----
try {
    for (int i = 1; i < 11; i++) {
        String v1 = doSomethingDangerous(i); // <1>
        String v2 = doSecondTransform(v1); // <2>
        System.out.println("RECEIVED " + v2);
    }
} catch (Throwable t) {
    System.err.println("CAUGHT " + t); // <3>
}
----
<1> 如果这里抛出异常...
<2> ...后续的代码跳过...
<3> ... 执行过程直接到这
====

既然我们准备了两种方式做对比,我们就来看一下不同的错误处理场景,以及相应的操作符.

==== 静态默认值

与第 (1) 条(捕获并返回一个静态的默认值)对应的是 `onErrorReturn`:

====
[source,java]
----
try {
  return doSomethingDangerous(10);
}
catch (Throwable error) {
  return "RECOVERED";
}
----
====

以下示例显示了 Reactor 的如何操作:

====
[source,java]
----
Flux.just(10)
    .map(this::doSomethingDangerous)
    .onErrorReturn("RECOVERED");
----
====

您还可以选择对异常进行 `Predicate` ,以决定是否要恢复,如以下示例所示:

====
[source,java]
----
Flux.just(10)
    .map(this::doSomethingDangerous)
    .onErrorReturn(e -> e.getMessage().equals("boom10"), "recovered10"); //<1>
----
<1> 仅在异常消息为 `"boom10"` 时恢复
====

==== 捕获和接收错误

如果您不想用回退值替换异常，而是忽略它并只传播到目前为止已经产生的元素，你想要的基本上是替换带有 `onComplete` 信号的 `onError` 信号。 这可以通过 `onErrorComplete` 运算符来完成：

====
[source,java]
----
Flux.just(10,20,30)
    .map(this::doSomethingDangerousOn30)
    .onErrorComplete(); //<1>
----
<1> 通过将 `onError` 变成 `onComplete` 来恢复
====

与 `onErrorReturn` 一样，`onErrorComplete` 有一些方法可以让你过滤哪些异常基于异常的类或 `Predicate` 来回退。

==== 异常处理方法

如果你不只是想要在发生错误的时候给出默认值,而是希望提供一种更安全的处理数据的方式, 可以使用 `onErrorResume`.这与第 (2) 条(捕获并执行一个异常处理方法)类似.

假设,你会尝试从一个外部的不稳定服务获取数据,但仍然会在本地缓存一份 可能 有些过期的数据, 因为缓存的读取更加可靠.可以这样来做:

====
[source,java]
----
String v1;
try {
  v1 = callExternalService("key1");
}
catch (Throwable error) {
  v1 = getFromCache("key1");
}

String v2;
try {
  v2 = callExternalService("key2");
}
catch (Throwable error) {
  v2 = getFromCache("key2");
}
----
====

以下示例显示了 Reactor 的实现方式:

====
[source,java]
----
Flux.just("key1", "key2")
    .flatMap(k -> callExternalService(k) // <1>
        .onErrorResume(e -> getFromCache(k)) // <2>
    );
----
<1> 对于每个 key,异步调用  external service.
<2> 如果对外部服务的调用失败,则再去缓存中查找该 key.注意,这里无论 `e` 是什么,都会执行异常处理方法.
====

就像 `onErrorReturn`,`onErrorResume` 也有可以用于预先过滤错误内容的方法变体,可以基于异常类或 `Predicate` 进行过滤.它实际上是用一个 `Function` 来作为参数,还可以返回一个新的流序列.

====
[source,java]
----
Flux.just("timeout1", "unknown", "key2")
    .flatMap(k -> callExternalService(k)
        .onErrorResume(error -> { // <1>
            if (error instanceof TimeoutException) // <2>
                return getFromCache(k);
            else if (error instanceof UnknownKeyException)  // <3>
                return registerNewEntry(k, "DEFAULT");
            else
                return Flux.error(error); // <4>
        })
    );
----
<1> 这个函数式允许开发者自行决定如何处理
<2> 如果源超时,使用本地缓存
<3> 	如果源找不到对应的 key,创建一个新的实体.
<4> 否则, 将问题 `"重新抛出"`.
====

==== 动态候补值

有时候并不想提供一个错误处理方法,而是想在接收到错误的时候计算一个候补的值.这类似于第 (3) 条(捕获并动态计算一个候补值).

例如,如果你的返回类型本身就有可能包装有异常(比如 `Future.complete(T success)` vs `Future.completeExceptionally(Throwable error)` ),你有可能使用流中的错误包装起来实例化 返回值.

示例代码如下:

====
[source,java]
----
try {
  Value v = erroringMethod();
  return MyWrapper.fromValue(v);
}
catch (Throwable error) {
  return MyWrapper.fromError(error);
}
----
====

这也可以使用上一种错误处理方法的方式(使用 `onErrorResume`)解决,代码如下:

====
[source,java]
----
erroringFlux.onErrorResume(error -> Mono.just( // <1>
        MyWrapper.fromError(error) // <2>
));
----
<1> 由于我们希望使用 `MyWrapper` 表示错误,,在 `onErrorResume` 中,使用 `Mono.just` 创建一个 `Mono<MyWrapper>`
<2> 我们需要计算异常值.在这里,我们通过使用相关的 `MyWrapper` 工厂方法包装异常来实现这一点.
====

==== 捕获并重新抛出

捕获,包装到 `BusinessException` 并重新抛出.如下所示:

====
[source,java]
----
try {
  return callExternalService(k);
}
catch (Throwable error) {
  throw new BusinessException("oops, SLA exceeded", error);
}
----
====

在 "`错误处理方法`" 的例子中,基于 `flatMap` 方法的最后一行,我们可以猜到如何做到第 (4) 条(捕获,包装到一个业务相关的异常,然后抛出 `BusinessException`):

====
[source,java]
----
Flux.just("timeout1")
    .flatMap(k -> callExternalService(k))
    .onErrorResume(original -> Flux.error(
            new BusinessException("oops, SLA exceeded", original))
    );
----
====

然而还有一个更加直接的方法 —— `onErrorMap`:

====
[source,java]
----
Flux.just("timeout1")
    .flatMap(k -> callExternalService(k))
    .onErrorMap(original -> new BusinessException("oops, SLA exceeded", original));
----
====

==== 记录错误日志

对于希望错误继续传播但仍希望对它作出反应而又不修改顺序(例如记录错误)的情况,可以使用doOnError运算符. 这等效于“捕获,记录特定于错误的消息并重新抛出”模式,如以下示例所示:

如果对于错误你只是想在不改变它的情况下做出响应(如记录日志),并让错误继续传递下去, 那么可以用 `doOnError` 方法.这对应第 (5) 条(捕获,记录错误日志,并继续抛出).如以下示例所示

====
[source,java]
----
try {
  return callExternalService(k);
}
catch (RuntimeException error) {
  //make a record of the error
  log("uh oh, falling back, service failed for key " + k);
  throw error;
}
----
====

这个方法与其他以 `doOn` 开头的方法一样,只起副作用("side-effect").它们对序列都是只读, 而不会带来任何改动.

如下边的例子所示,我们会记录错误日志

====
[source,java]
----
LongAdder failureStat = new LongAdder();
Flux<String> flux =
Flux.just("unknown")
    .flatMap(k -> callExternalService(k) // <1>
        .doOnError(e -> {
            failureStat.increment();
            log("uh oh, falling back, service failed for key " + k); // <2>
        })
        // <3>
    );
----
<1> 对外部服务的调用失败...
<2> ...记录错误日志...
<3> ...然后回调错误处理方法.
====

并且还通过变量自增统计错误发生个数.

==== 使用资源和 try-catch 代码块

最后一个要与命令式编程对应的对比就是使用 Java 7 "try-with-resources" 或 `finally` 代码块清理资源.这是第 (6) 条(使用 `finally` 代码块清理资源或使用 Java 7 引入的 "try-with-resource").

.Imperative use of finally
====
[source,java]
----
Stats stats = new Stats();
stats.startTimer();
try {
  doSomethingDangerous();
}
finally {
  stats.stopTimerAndRecordTiming();
}
----
====

.Imperative use of try-with-resource
====
[source,java]
----
try (SomeAutoCloseable disposableInstance = new SomeAutoCloseable()) {
  return disposableInstance.toString();
}
----
====

在 Reactor 中都有对应的方法:  `using` 和 `doFinally`:

另一方面, `doFinally` 在序列终止(无论是 `onComplete`、`onError` 还是取消)的时候被执行, 并且能够判断是什么类型的终止事件(完成、错误还是取消? ).

====
[source,java]
.Reactive finally: `doFinally()`
----
Stats stats = new Stats();
LongAdder statsCancel = new LongAdder();

Flux<String> flux =
Flux.just("foo", "bar")
    .doOnSubscribe(s -> stats.startTimer())
    .doFinally(type -> { // <1>
        stats.stopTimerAndRecordTiming();// <2>
        if (type == SignalType.CANCEL) // <3>
          statsCancel.increment();
    })
    .take(1); // <4>
----
<1> `doFinally` 用 `SignalType` 检查了终止信号的类型.
<2> 与 `finally` 块类似,我们总是记录时间.
<3> 如果只是取消,那么统计数据自增.
<4> `take(1)` 能够从上游请求 1 个元素后取消流.
====

另一方面,`using` 能处理从 `Flux` 产生的资源,并且每当处理完成时都必须对资源进行操作. 在以下示例中,我们用 `Disposable` 替换了  "`try-with-resource`"  的 `AutoCloseable` 接口:

.The Disposable resource
====
[source,java]
----
AtomicBoolean isDisposed = new AtomicBoolean();
Disposable disposableInstance = new Disposable() {
    @Override
    public void dispose() {
        isDisposed.set(true); // <4>
    }

    @Override
    public String toString() {
        return "DISPOSABLE";
    }
};
----
====

现在,我们可以在上面进行等效的  "`try-with-resource`"  尝试,如下所示:

.Reactive try-with-resource: `using()`
====
[source,java]
----
Flux<String> flux =
Flux.using(
        () -> disposableInstance, // <1>
        disposable -> Flux.just(disposable.toString()), // <2>
        Disposable::dispose // <3>
);
----
<1> 第一个 lambda 生成资源,这里我们返回模拟的(mock) `Disposable`.
<2> 第二个 lambda 处理资源,返回一个 `Flux<T>`.
<3> 第三个 lambda 在 2) 中的资源 `Flux` 终止或取消的时候,用于清理资源
<4> 在订阅或执行流序列之后, isDisposed 会置为 `true`.
====

==== 演示终止方法 `onError`

为了演示当错误出现的时候如何导致上游序列终止,我们使用 `Flux.interval` 构造一个更加直观的例子. 这个 `interval` 操作符会在每 `x` 单位的时间发出一个自增的 `Long` 值.

====
[source,java]
----
Flux<String> flux =
Flux.interval(Duration.ofMillis(250))
    .map(input -> {
        if (input < 3) return "tick " + input;
        throw new RuntimeException("boom");
    })
    .onErrorReturn("Uh oh");

flux.subscribe(System.out::println);
Thread.sleep(2100); // <1>
----
<1> 注意 interval 默认基于一个  *timer* `Scheduler` 来执行. 如果我们想在 main 方法中运行, 我们需要调用 `sleep`,这样程序就可以在还没有产生任何值的时候就退出了.
====

每 250ms 打印出一行信息,如下:

====
[source]
----
tick 0
tick 1
tick 2
Uh oh
----
====

即使多给了 1 秒钟时间,也没有更多的 tick 信号由 `interval` 产生了,所以序列确实被错误信号终止了.

==== 重试

还有一个用于错误处理的操作符你可能会用到,就是 `retry`,见文知意,用它可以对出现错误的序列进行重试.

问题是它对于上游 `Flux` 是基于重订阅(*re-subscribing*)的方式.这实际上已经一个不同的序列了, 发出错误信号的序列仍然是终止了的.为了验证这一点,我们可以在继续用上边的例子,增加一个 `retry(1)` 代替 `onErrorReturn` 来重试一次.

====
[source,java]
----
Flux.interval(Duration.ofMillis(250))
    .map(input -> {
        if (input < 3) return "tick " + input;
        throw new RuntimeException("boom");
    })
    .retry(1)
    .elapsed() // <1>
    .subscribe(System.out::println, System.err::println); // <2>

Thread.sleep(2100); // <3>
----
<1> `elapsed` 会关联从当前值与上个值发出的时间间隔(译者加: 如下边输出的内容中的 259/249/251…)
<2> 我们还是要看一下 `onError` 时的内容.
<3> 确保我们有足够的时间可以进行 4x2 次 tick.
====

输出如下

====
[source]
----
259,tick 0
249,tick 1
251,tick 2
506,tick 0 <1>
248,tick 1
253,tick 2
java.lang.RuntimeException: boom
----
<1> 一个新的 `interval` 从 tick 0 开始.多出来的 250ms 间隔来自于第 4 次 tick, 就是导致出现异常并执行 `retry` 的那次.
====

可见, `retry(1)` 不过是再一次从新订阅了原始的 `interval`,从 tick 0 开始.第二次, 由于异常再次出现,便将异常传递到下游了.

还有一个 "`高配版`" 的 `retry` (`retryWhen`),它使用一个伴随("`companion`") `Flux` 来判断对某次错误是否要重试.这个伴随 `Flux` 是由操作符创建的,但是由开发者包装它, 从而实现对重试操作的配置.

这个伴随 `Flux` 是一个 `Flux<RetrySignal>`,它作为 `retryWhen` 的唯一参数被传递给一个 `Retry` strategy/function,你可以定义这个函数并让它返回一个新的 `Publisher<?>`.
`Retry` 类是一个抽象类,但是如果您想用一个简单的 lambda (`Retry.from(Function)`) 转换,它提供了一个工厂方法.

重试周期如下:

. 每次出现错误,都会将 `RetrySignal` 信号会发送给伴随 `Flux`,后者已经被你的方法包装.在 `Flux` 可以看到目前为止所有的尝试,`RetrySignal` 允许访问错误以及错误周围的元数据.
. 如果伴随 `Flux` 发出元素,就会触发重试.
. 如果伴随 `Flux` 完成(complete),重试循环也会停止,并且原始序列也会 完成(complete)
. 如果伴随 Flux 产生一个错误( `e` ),则重试周期停止,结果序列错误为 `e`.

了解前两个场景的区别是很重要的.如果让伴随 Flux 完成(complete)等于吞掉了错误.如下代码用 `retryWhen` 模仿了 `retry(3)` 的效果:

====
[source,java]
----
Flux<String> flux = Flux
    .<String>error(new IllegalArgumentException()) // <1>
    .doOnError(System.out::println) // <2>
    .retryWhen(Retry.from(companion -> // <3>
        companion.take(3))); // <4>
----
<1> 持续产生错误.
<2> 在 retry 之前 的 `doOnError` 可以让我们看到错误.
<3> `Retry` 适配自一个非常简单的lambda `Function`
<4> 这里,我们认为前 3 个错误是可以重试的(`take(3)`),再有错误就放弃.
====

事实上,上边例子最终得到的是一个 空的 `Flux`,但是却 成功 完成了.反观对同一个 `Flux` 调用 `retry(3)` 的话,最终是以最后一个 error 终止 Flux,故而 `retryWhen` 与之不同.

实现同样的效果需要一些额外的技巧:
include::snippetRetryWhenRetry.adoc[]

TIP: 可以使用  `Retry` 中暴露的构建器以更流畅的方式以及更精细的重试策略来实现相同目标.例如: `errorFlux.retryWhen(Retry.max(3));`.

TIP: 类似的代码也可以被用于实现 "`exponential backoff and retry`" 模式 (译者加: 重试指定的次数, 且每一次重试之间停顿的时间逐渐增加),参考 <<faq.exponentialBackoff,FAQ>>.

core 包中提供的 `Retry` helpers , `RetrySpec` 和 `RetryBackoffSpec` 都允许高级自定义,例如:

- 为可能触发重试的异常设置 `filter(Predicate)`
- 通过 `modifyErrorFilter(Function)` 修改类似上一条中设置的过滤器
- 触发副作用,例如在重试触发器周围记录日志(即在延迟之前和之后进行回退),前提是重试已通过验证(`doBeforeRetry()` 和 `doAfterRetry()` 都符合)
- 在重试触发器周围触发异步 `Mono<Void>`,这允许在基本延迟之上添加异步行为,但因此进一步延迟了触发器( `doBeforeRetryAsync` 和 `doAfterRetryAsync` 是符合)
- 通过 `onRetryExhaustedThrow(BiFunction)` 自定义异常(如果已达到最大尝试次数).默认情况下,使用  `Exceptions.retryExhausted(...)`,可以通过 `Exceptions.isRetryExhausted(Throwable)` 进行区分
- 激活  _transient errors_  的处理(请参见下文)(see below)

===== 重试 transient errors（瞬态错误 ）

一些长期存在的源可能会看到零星突发错误，然后是一段较长的时间，在此期间一切都在平稳运行。本文档将这种错误模式称为 _transient errors_ （瞬态错误）。

在这种情况下，最好单独处理每个突发错误，以便下一个突发不会继承前一个突发的重试状态。例如，使用 exponential backoff （指数退避）策略，
这还意味着下一次尝试将回到使用最小的 `Duration` 开始重新延时重试,而不是更长的 `Duration`.。

`RetrySignal` 接口 表示 `retryWhen` 状态，他有一个 `totalRetriesInARow()` 值。与通常的单调递增的 `totalRetries()` 索引不同，每次出现错误时，该二级索引都会重置为 `0`
通过重试恢复（即，当尝试重试导致传入的 `onNext` 而不是再次出现 `onError` 时）。

当在  `RetrySpec`  或 `RetryBackoffSpec` 中将 `transientErrors(boolean)` 配置参数设置为 `true` 时，生成的策略会使用 `totalRetriesInARow()` 索引，
从而有效地处理 _transient errors_。 这些规范根据索引计算重试模式，因此实际上规范的所有其他配置参数都独立应用于每个突发错误。

====
[source,java]
----
AtomicInteger errorCount = new AtomicInteger(); // <1>
Flux<Integer> transientFlux = httpRequest.get() // <2>
        .doOnError(e -> errorCount.incrementAndGet());

transientFlux.retryWhen(Retry.max(2).transientErrors(true))  // <3>
             .blockLast();
assertThat(errorCount).hasValue(6); // <4>
----
<1> 我们将计算重试序列中的错误数.
<2> 我们假设一个 http 请求是一个流端点，有时会连续失败两次，然后恢复。
<3> 我们在该请求上使用 `retryWhen` 配置为最多 2 次重试，但处于 `transientErrors` 模式。.
<4> 最后，在 `errorCount` 中注册了 `6` 次尝试后，将获得有效响应，并且 `transientFlux` 成功完成。
====

如果没有 `transientErrors(true)`,则第二个突发将达到配置的最大尝试次数 `2`, 整个序列最终将失败。.

[NOTE]
====
如果您想在没有实际 http 远程端点的情况下在本地尝试此操作，您可以将伪 `httpRequest` 方法实现为 `Supplier`，如下所示：

=====
[source,java]
----
final AtomicInteger transientHelper = new AtomicInteger();
Supplier<Flux<Integer>> httpRequest = () ->
    Flux.generate(sink -> { // <1>
        int i = transientHelper.getAndIncrement();
        if (i == 10) { // <2>
            sink.next(i);
            sink.complete();
        }
        else if (i % 3 == 0) { // <3>
            sink.next(i);
        }
        else {
            sink.error(new IllegalStateException("Transient error at " + i)); // <4>
        }
    });
----
<1> 我们 `generate` 的源中包含大量错误
<2> 当计数器达到 10 时,它将成功完成.
<3> 如果 `transientHelper` atomic 是 3 的倍数,则我们发出 `onNext` 并因此结束当前突发.
<4> 在其他情况下,我们发出一个 `onError`.因为 2 不是 3 的倍数,因此 2 个 `onError` 突发被 1 个 `onNext` 中断.
=====
====

=== 在操作符或函数式中处理异常

总体来说,所有的操作符自身都可能包含触发异常的代码,或自定义的可能导致失败的代码, 所以它们都自带一些错误处理方式.

一般来说,一个 不受检异常(Unchecked Exception) 总是由 `onError` 传递.例如, 在一个 `map` 方法中抛出 `RuntimeException` 会被翻译为一个 `onError` 事件,如下:

====
[source,java]
----
Flux.just("foo")
    .map(s -> { throw new IllegalArgumentException(s); })
    .subscribe(v -> System.out.println("GOT VALUE"),
               e -> System.out.println("ERROR: " + e));
----
====

上边代码输出如下:

====
[source]
----
ERROR: java.lang.IllegalArgumentException: foo
----
====

TIP: `Exception` 可以在其被传递给 `onError` 之前,使用 <<hooks-internal,hook>> 进行调整.

Reactor,定义了一系列的能够导致“严重失败”的错误(比如 `OutOfMemoryError`),也可参考 `Exceptions.throwIfFatal` 方法.这些错误意味着 Reactor 无力处理只能抛出,无法传递下去.

NOTE: 还有些情况下不受检异常仍然无法传递下去(多数处于 subscribe 和 request 阶段), 因为可能由于多线程竞争导致两次 `onError` 或 `onComplete` 的情况.当这种竞争发生的时候, 无法传递下去的错误信号就被 "`dropped`" 了.
这些情况仍然可以通过自定义的 hook 来搞定,见 丢弃事件的 <<hooks-dropping>>.

你可能会问: “那么 受检查异常(Checked Exceptions)? ”

如果你需要调用一个声明为 `throws` 异常的方法,你仍然需要使用 `try-catch` 代码块处理异常. 有几种方式:

. 捕获异常,并修复它,流序列正常继续.
. 捕获异常,并把它包装(wrap)到一个 不受检异常 中,然后抛出(中断序列).工具类 `Exceptions` 可用于这种方式(我们马上会讲到).
. 如果你需要我返回一个 `Flux` (例如在 `flatMap` 中),将异常包装在一个产生错误的 `Flux``中:  `return Flux.error(checkedException)`(流序列也会终止).

Reactor 有一个工具类 `Exceptions`,可以确保在收到受检异常的时候将其包装(wrap)起来.

* 如果需要,可以使用 `Exceptions.propagate` 方法来包装异常,它同样会首先调用 `throwIfFatal`, 并且不会包装 `RuntimeException`.
* 使用 `Exceptions.unwrap` 方法来得到原始的未包装的异常(追溯最初的异常).

下面是一个 `map` 的例子,它使用的 `convert` 方法会抛出 `IOException`:

====
[source,java]
----
public String convert(int i) throws IOException {
    if (i > 3) {
        throw new IOException("boom " + i);
    }
    return "OK " + i;
}
----
====

现在想象你将这个方法用于一个 `map` 中,你必须明确捕获这个异常,并且你的 `map` 方法不能再次抛出它. 所以你可以将其以 `RuntimeException` 的形式传递给 `onError`:

====
[source,java]
----
Flux<String> converted = Flux
    .range(1, 10)
    .map(i -> {
        try { return convert(i); }
        catch (IOException e) { throw Exceptions.propagate(e); }
    });
----
====

当后边订阅上边的这个 `Flux` 并响应错误(比如在用户界面)的时候,如果你想处理 IOException, 你还可以再将其转换为原始的异常.如下:

====
[source,java]
----
converted.subscribe(
    v -> System.out.println("RECEIVED: " + v),
    e -> {
        if (Exceptions.unwrap(e) instanceof IOException) {
            System.out.println("Something bad happened with I/O");
        } else {
            System.out.println("Something bad happened");
        }
    }
);
----
====

[[sinks]]
== Sinks

include::processors.adoc[leveloffset=3]